package day07

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

const example = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

func Test_Part1(t *testing.T) {
	assert.Equal(t, 21, countBeamSplits(example))
}

func Test_Part2(t *testing.T) {
	assert.Equal(t, 40, countTachyonTimelines(example))
}
